/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
export const jsonSchema: z.ZodType<unknown> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicGameTypeSchema = z.union([z.literal("guess_name"), z.literal("guess_image")]);

export const publicGenderTypeSchema = z.union([z.literal("male"), z.literal("female"), z.literal("other")]);

export const publicUserRoleSchema = z.union([z.literal("teacher"), z.literal("student")]);

export const publicGameAnswersRowSchema = z.object({
  answered_at: z.string().nullable(),
  correct_option_id: z.string().nullable(),
  created_at: z.string().nullable(),
  id: z.string(),
  is_active: z.boolean().nullable(),
  is_correct: z.boolean(),
  join_id: z.string().nullable(),
  player_name: z.string().nullable(),
  response_time_ms: z.number().nullable(),
  selected_option_id: z.string().nullable(),
  session_id: z.string(),
  updated_at: z.string().nullable(),
});

export const publicGameAnswersInsertSchema = z.object({
  answered_at: z.string().optional().nullable(),
  correct_option_id: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_active: z.boolean().optional().nullable(),
  is_correct: z.boolean(),
  join_id: z.string().optional().nullable(),
  player_name: z.string().optional().nullable(),
  response_time_ms: z.number().optional().nullable(),
  selected_option_id: z.string().optional().nullable(),
  session_id: z.string(),
  updated_at: z.string().optional().nullable(),
});

export const publicGameAnswersUpdateSchema = z.object({
  answered_at: z.string().optional().nullable(),
  correct_option_id: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_active: z.boolean().optional().nullable(),
  is_correct: z.boolean().optional(),
  join_id: z.string().optional().nullable(),
  player_name: z.string().optional().nullable(),
  response_time_ms: z.number().optional().nullable(),
  selected_option_id: z.string().optional().nullable(),
  session_id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicGameAnswersRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("game_answers_correct_option_id_fkey"),
    columns: z.tuple([z.literal("correct_option_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("people"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("game_answers_selected_option_id_fkey"),
    columns: z.tuple([z.literal("selected_option_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("people"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("game_answers_session_id_fkey"),
    columns: z.tuple([z.literal("session_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("game_sessions"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicGameSessionsRowSchema = z.object({
  completed_at: z.string().nullable(),
  enable_timer: z.boolean().nullable(),
  game_code: z.string().nullable(),
  game_type: publicGameTypeSchema,
  group_id: z.string(),
  id: z.string(),
  options_count: z.number().nullable(),
  score: z.number().nullable(),
  started_at: z.string().nullable(),
  status: z.string().nullable(),
  time_limit_seconds: z.number().nullable(),
  total_questions: z.number().nullable(),
  user_id: z.string().nullable(),
});

export const publicGameSessionsInsertSchema = z.object({
  completed_at: z.string().optional().nullable(),
  enable_timer: z.boolean().optional().nullable(),
  game_code: z.string().optional().nullable(),
  game_type: publicGameTypeSchema,
  group_id: z.string(),
  id: z.string().optional(),
  options_count: z.number().optional().nullable(),
  score: z.number().optional().nullable(),
  started_at: z.string().optional().nullable(),
  status: z.string().optional().nullable(),
  time_limit_seconds: z.number().optional().nullable(),
  total_questions: z.number().optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const publicGameSessionsUpdateSchema = z.object({
  completed_at: z.string().optional().nullable(),
  enable_timer: z.boolean().optional().nullable(),
  game_code: z.string().optional().nullable(),
  game_type: publicGameTypeSchema.optional(),
  group_id: z.string().optional(),
  id: z.string().optional(),
  options_count: z.number().optional().nullable(),
  score: z.number().optional().nullable(),
  started_at: z.string().optional().nullable(),
  status: z.string().optional().nullable(),
  time_limit_seconds: z.number().optional().nullable(),
  total_questions: z.number().optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const publicGameSessionsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("game_sessions_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("groups"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicGroupPeopleRowSchema = z.object({
  created_at: z.string().nullable(),
  group_id: z.string(),
  id: z.string(),
  person_id: z.string(),
});

export const publicGroupPeopleInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  group_id: z.string(),
  id: z.string().optional(),
  person_id: z.string(),
});

export const publicGroupPeopleUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  group_id: z.string().optional(),
  id: z.string().optional(),
  person_id: z.string().optional(),
});

export const publicGroupPeopleRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("group_people_group_id_fkey"),
    columns: z.tuple([z.literal("group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("groups"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("group_people_person_id_fkey"),
    columns: z.tuple([z.literal("person_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("people"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicGroupsRowSchema = z.object({
  created_at: z.string().nullable(),
  creator_id: z.string(),
  enable_timer: z.boolean().nullable(),
  id: z.string(),
  name: z.string(),
  options_count: z.number().nullable(),
  share_code: z.string().nullable(),
  time_limit_seconds: z.number().nullable(),
  updated_at: z.string().nullable(),
});

export const publicGroupsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  creator_id: z.string(),
  enable_timer: z.boolean().optional().nullable(),
  id: z.string().optional(),
  name: z.string(),
  options_count: z.number().optional().nullable(),
  share_code: z.string().optional().nullable(),
  time_limit_seconds: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const publicGroupsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  creator_id: z.string().optional(),
  enable_timer: z.boolean().optional().nullable(),
  id: z.string().optional(),
  name: z.string().optional(),
  options_count: z.number().optional().nullable(),
  share_code: z.string().optional().nullable(),
  time_limit_seconds: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const publicPeopleRowSchema = z.object({
  created_at: z.string().nullable(),
  gender: publicGenderTypeSchema,
  id: z.string(),
  image_url: z.string().nullable(),
  name: z.string(),
  updated_at: z.string().nullable(),
});

export const publicPeopleInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  gender: publicGenderTypeSchema,
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  name: z.string(),
  updated_at: z.string().optional().nullable(),
});

export const publicPeopleUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  gender: publicGenderTypeSchema.optional(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  name: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicProfilesRowSchema = z.object({
  avatar_url: z.string().nullable(),
  created_at: z.string().nullable(),
  email: z.string().nullable(),
  first_name: z.string().nullable(),
  id: z.string(),
  last_name: z.string().nullable(),
  role: publicUserRoleSchema.nullable(),
  updated_at: z.string().nullable(),
});

export const publicProfilesInsertSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  first_name: z.string().optional().nullable(),
  id: z.string(),
  last_name: z.string().optional().nullable(),
  role: publicUserRoleSchema.optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const publicProfilesUpdateSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  first_name: z.string().optional().nullable(),
  id: z.string().optional(),
  last_name: z.string().optional().nullable(),
  role: publicUserRoleSchema.optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const publicGenerateGameCodeArgsSchema = z.never();

export const publicGenerateGameCodeReturnsSchema = z.string();

// =============================
// Custom Schemas for Queries
// =============================

// GameSession schema (row)
export const gameSessionSchema = publicGameSessionsRowSchema;
export type GameSession = z.infer<typeof gameSessionSchema>;

// GameSession with group details (for joined queries)
export const gameSessionWithGroupSchema = z.object({
  ...publicGameSessionsRowSchema.shape,
  groups: z
    .object({
      id: z.string(),
      name: z.string(),
    })
    .nullable(),
});
export type GameSessionWithGroup = z.infer<typeof gameSessionWithGroupSchema>;

// Group schema (row)
export const groupSchema = publicGroupsRowSchema;
export type Group = z.infer<typeof groupSchema>;

// Person schema (row)
export const personSchema = publicPeopleRowSchema;
export type Person = z.infer<typeof personSchema>;

// Utility: parseOrNull - validates data or returns null
export function parseOrNull<T>(schema: z.ZodType<T>, data: unknown): T | null {
  if (!data) return null;
  const result = schema.safeParse(data);
  return result.success ? result.data : null;
}

// Utility: parseArrayFiltered - validates array, filters out invalid
export function parseArrayFiltered<T>(schema: z.ZodType<T>, data: unknown): T[] {
  if (!Array.isArray(data)) return [];
  return data
    .map((item: unknown): T | null => {
      const result = schema.safeParse(item);
      return result.success ? result.data : null;
    })
    .filter((item: T | null): item is T => item !== null);
}

// Aliases for compatibility with existing imports
export type GameType = z.infer<typeof publicGameTypeSchema>;
export type PersonInsert = z.infer<typeof publicPeopleInsertSchema>;
export type GenderType = z.infer<typeof publicGenderTypeSchema>;
